In [1]:
import numpy as np

In [2]:
#for char to int where a=0...z=25
def charToInt(s):
    value=ord(s)-ord('a')
    return value

#for int to char where 0=a...25=z
def intTochar(s):
    return chr(s%26 +ord('a'))

In [3]:
def keyInput():
    print("ENTER KEY SIZE 'N' for NXN KEY MATRIX")
    keySize=int(input())
    print("ENTER THE KEY")
    keyString=input()
    if len(keyString) !=keySize**2 :
        return "ERROR IN KEY! CHECK KEY SIZE AGAIN"
    else:
        keyList=list(map(charToInt,list(keyString)))
        key=np.reshape(np.array(keyList),(keySize,keySize))
        return key,keySize

In [4]:
def plainText():
    print("ENTER THE PLAIN TEXT")
    text=input()
    return list(map(charToInt,list(text)))

In [5]:
# Ax+My = 1 = gcd(A,M) = gcd(M,A%M)
x=1
y=0
cf=0
def gcd(A,M):
    global x
    global y
    global cf
    if M==0:
        x=1
        y=0
        cf=A
    else:
        gcd(M,A%M)
        temp=x
        x=y
        y=temp-(A//M)*y
#         print(x,y,cf)

In [6]:
#takes input key and plaintext in "int np.array" format
def encryption(K,P):
    CT=[np.dot(K,PT) for PT in P]
    return list(map(intTochar,list(np.reshape(CT,(1,-1)).flat)))

In [7]:
##takes input key and cpherText in" int np.array" format
def decryption(K,C):
    PT=[np.dot(K,CT) for CT in C]
    return list(map(intTochar,list(np.reshape(PT,(1,-1)).flat)))

In [9]:
(key,keySize) = keyInput()
print(keySize)
print(key)
plaintext=plainText()
plainTextList = np.reshape(plaintext,(-1,keySize))
print(plainTextList)
cipherText = encryption(key,plainTextList)
print("chiptext text is {} ".format(cipherText))
det=np.round(np.linalg.det(key))

gcd(det,26)
if(cf!=1):
    print("tatti key")
    exit()
print("det{} ".format(det))
invKey=np.linalg.inv(key)
print(invKey)
adj=invKey*det*(x%26) #cf is the modular inverse of det w.r.t 26
cipherTextMatrix=np.reshape(np.array(list(map(charToInt,cipherText))),(-1,keySize))
print(cipherTextMatrix)
# print(adj.astype(int)%26)
adj=adj.astype(int)%26
print("adj {}".format(adj))
plainTextList=decryption(adj,cipherTextMatrix)
print(plainTextList)

ENTER KEY SIZE 'N' for NXN KEY MATRIX
2
ENTER THE KEY
abcd
2
[[0 1]
 [2 3]]
ENTER THE PLAIN TEXT
viveksingh
[[21  8]
 [21  4]
 [10 18]
 [ 8 13]
 [ 6  7]]
chiptext text is ['i', 'o', 'e', 'c', 's', 'w', 'n', 'd', 'h', 'h'] 
tatti key
det-2.0 
[[-1.5  0.5]
 [ 1.   0. ]]
[[ 8 14]
 [ 4  2]
 [18 22]
 [13  3]
 [ 7  7]]
adj [[23  1]
 [ 2  0]]
['q', 'q', 'q', 'i', 'u', 'k', 'q', 'a', 'm', 'o']
